-- ui
MOUSEBUTTON_LEFT = 1
MOUSEBUTTON_RIGHT = 2
MOUSEBUTTON_MIDDLE = 3

-- console
CON_ARCHIVE = 0b0001
CON_SYNC = 0b0010
CON_SERVER = 0b0100
CON_CLIENT = 0b1000

-- directions
DIRECTION_RIGHT = 0
DIRECTION_LEFT = 1
DIRECTION_UP = 2
DIRECTION_DOWN = 3

-- network
NETWORK_DEFAULT_PORT = 14700

NETWORK_DISCONNECT_UNKNOWN = 0
NETWORK_DISCONNECT_KICKED = 1
NETWORK_DISCONNECT_TIMEOUT = 2
NETWORK_DISCONNECT_USER = 3
NETWORK_DISCONNECT_SHUTDOWN = 4

NETWORK_TYPE = {
	RAW = 0,
	BOOL = 1,
	STRING = 2,

	BYTE = 3,
	USHORT = 4,
	SHORT = 5,
	UINT = 6,
	INT = 7,
	ULONG = 8,
	LONG = 9,
	FLOAT = 10,
	DOUBLE = 11,

	VECTOR2 = 12,
	VECTOR2I = 13,
	COLOR = 14,
}

-- viewport
-- tg's viewport base width and height
VIEWPORT_WIDTH = 608
VIEWPORT_HEIGHT = 480
